builds:
  - binary: esmjs
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=readonly

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -`
    name: esmjs
    homepage: "https://github.com/naecoo/esmjs"
    repository:
      owner: naecoo
      name: homebrew-esmjs
    commit_author:
      name: naecoo
      email: ocean7hy@gmail.com

checksum:
  name_template: 'checksums.txt'